apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pwpush-pro.fullname" . }}-config
  labels:
    {{- include "pwpush-pro.labels" . | nindent 4 }}
data:
  PORT: "80"
  RAILS_ENV: "production"
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
