apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pwpush-pro.fullname" . }}-storage
  labels:
    {{- include "pwpush-pro.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
